{{ config(materialized="table") }}

SELECT
    brasil_grande_regiao_unidade_federacao_municipio,
    area_urbana_0_a_10,
    area_rural_0_a_10,
    terras_indigenas_0_a_10,
    territorios_quilobolas_0_a_10,
    favelas_comundades_urbanas_0_a_10,
    area_urbana_11_a_18,
    area_rural_11_a_18,
    terras_indigenas_11_a_18,
    territorios_quilobolas_11_a_18,
    favelas_comundades_urbanas_11_a_18,
    area_urbana_19_a_39,
    area_rural_19_a_39,
    terras_indigenas_19_a_39,
    territorios_quilobolas_19_a_39,
    favelas_comundades_urbanas_19_a_39,
    area_urbana_40_a_59,
    area_rural_40_a_59,
    terras_indigenas_40_a_59,
    territorios_quilobolas_40_a_59,
    favelas_comundades_urbanas_40_a_59,
    area_urbana_60_a_79,
    area_rural_60_a_79,
    terras_indigenas_60_a_79,
    territorios_quilobolas_60_a_79,
    favelas_comundades_urbanas_60_a_79,
    mais_area_urbana_80,
    mais_area_rural_80,
    mais_terras_indigenas_80,
    mais_territorios_quilobolas_80,
    mais_favelas_comundades_urbanas_80,
    (dt_ingest || '-03:00')::timestamptz AS dt_ingest,
    nome_fonte
FROM {{ source("censo_demografico", "mulheres_tabela_17_br_gr_uf_mu") }}
